### ISSUE TITLE
2.2.0 - Agents et fiches intervention (popup)

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/Police#14]
Les agents ne remontent pas dans le fichier /fiche_intervention.php
C'est OK dans la fiche affichée en pleine page (impression)

**Comment by camillemonchicourt** [comment]
Idem dans/popup_intervention_agent_suppr.php
Quand on supprime un agent d'une intervention.

**Comment by gildeluermoz** [comment]
close with 3b865b818c11205c3999c0bf5071ab7ae3c75c3e
