### ISSUE TITLE
2.2.0 - Affichage "aucune infraction"

### ISSUE THREAD

**Issue by camillemonchicourt** [PnEcrins/Police#15]
Dans la liste des interventions mais potentiellement dans les export. 
Afficher "aucun" plutôt que " / "

Ou laisser vide. Idem pour les agents présents. 

Le mieux serait certainement de ne pas permettre de na pas saisir d'agent et/ou d'infraction - https://github.com/PnEcrins/Police/issues/8

**Comment by gildeluermoz** [comment]
La résolution de la #8 devrait résoudre ça pour les nouvelles infrations. Pour les anciennes, on va dire tant pis ! A Voir

**Comment by camillemonchicourt** [comment]
Top
