### ISSUE TITLE
CARTO - Le lien de la librairie ol 2.11 n'est plus valide

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/Police#18]

**Comment by camillemonchicourt** [comment]
Cool, il faut qu'on sorte la 2.3.2 du coup !

**Comment by gildeluermoz** [comment]
oui, tu l'as fais ? Pour moi tout est corrigé et commité ainsi qu'un bug d'interaction avec la carte sur le 6 qui ne s'écrivait pas et qui agissait sur un dézoom de la carte. Signalé par Nils Paulet.

**Comment by camillemonchicourt** [comment]
OK je m'en charge.

**Comment by gildeluermoz** [comment]
Ca marche. Merci
